###
POST http://localhost:3000/prendas
Content-Type: application/json

{
    "nombre":"Bakend Untref",
    "precio":"5000",
    "categoria":"Remera"
}

###
GET http://localhost:3000/prendas/all



###

DELETE http://localhost:3000/prendas/id/66ab949d15ff59d997f7c201

###
PATCH http://localhost:3000/prendas/Modifict/66ab949d15ff59d997f7c201
Content-Type: application/json

{
   "precio":"12"
}

###
POST  http://localhost:3000/login
Content-Type: application/json

{
    "nombre":"jesus",
    "clave":1234
}

###
GET http://localhost:3000/Desconexion







