process.loadEnvFile()
const express = require ('express')
const mongoose=require('mongoose')
const cookieParser= require ('cookie-parser')
const app=express()
const port=process.env.PORT
const morgan=require ('morgan')
const inicio=require('./rutas/inicio.js')
const PrendasAll=require('./rutas/all.js')
const PrendasId=require('./rutas/ID.js')
const actualizar=require('./rutas/actualizar.js')
const login=require('./rutas/login.js')
const desconex=require('./rutas/desconex.js')
const Crear=require('./rutas/crear.js')
const eliminar=require('./rutas/eliminar.js')
const nombre=require('./rutas/nombre.js')
const autorizacion=require('./rutas/autorizacion.js')

app.use(morgan('dev'))
app.use(express.json())
app.use(cookieParser())
app.use(express.urlencoded({ extended: true }))

app.use('/',inicio)
app.use('/prendas/all',autorizacion,PrendasAll)
app.use('/prendas/id/:id',autorizacion,PrendasId)
app.use('/prendas/nombre/:nombre',autorizacion,nombre)
app.use('/prendas/Modifict/:id',autorizacion,actualizar)
app.use('/login',login)
app.use('/Desconexion',desconex)
app.use('/prendas',autorizacion,Crear)
app.use('/prendas/id/:id',autorizacion,eliminar)

app.use((req,res)=>{
    res.status(400).json({mensaje:"Error 400"})
})

app.listen(port,()=>{
    console.log("puerto open")
})